USE kokebok;

INSERT INTO oppskrifter (Oppskriftstittel, Ingredienser, Allergier, Kategori, Oppskriftstekst)
VALUES ('Kålrabistappe', 'Kålrot, Gulrøtter, Fløte, Smør, Salt, Pepper', 'Laktose', 5, 'Kok kålrot og gulrøtter. Mos mens du tilsetter smør og sper med fløte. Smak til med salt og pepper.'),
       ('Gulrotsuppe', 'Gulrøtter, Currypaste, Smør, Salt, Pepper, Hvitløk, Løk, Kokosmelk', '', 11, 'Smelt smør og stek løk til den er blank. Ha i hvitløk og stek i 1 minutt. Ha i currypaste og stek i 2 minutter. Ha i kokosmelk og oppkuttede gulrøtter og kok i 20-30 minutter til gulrøttene er møre. Bruk stavmikser for å få en jevn suppe. Smak til med salt og pepper.'),
       ('Lynrask linsegryte', 'Hermetiske røde linser, Buljongterning, Currypaste, Olje, Salt, Pepper, Hvitløk, Løk, Kokosmelk, Hermetiske tomater', '', 3, 'Stek løk til den er blank. Ha i hvitløk og stek i 1 minutt. Ha i currypaste og stek i 2 minutter. Ha i buljong, kokosmelk og hermetiske tomater og kok opp i 5 minutter. Tilsett skylte linser. Smak til med salt og pepper.'),
       ('Bruschetta', 'Mozzarella, Cherrytomater, Olivenolje, Salt, Pepper, Hvitløk, Basilikum, Brød', 'Gluten', 0, 'Ta skivet brød, pensle med olivenolje og stek de raskt i ovnen. Bland hakkede tomater, olivenolje, finhakket hvitløk, hakket basilikum, salt og pepper i en bolle. Fordel blandingen på brødskivene og topp med noen skiver mozzarella.');

INSERT INTO oppskrifter (Oppskriftstittel, Ingredienser, Allergier, Kategori, Oppskriftstekst)
VALUES ('Kålrabistappe2', 'Kålrot, Gulrøtter, Fløte, Smør, Salt, Pepper', 'Laktose', 5, 'Kok kålrot og gulrøtter. Mos mens du tilsetter smør og sper med fløte. Smak til med salt og pepper.'),
       ('Gulrotsuppe2', 'Gulrøtter, Currypaste, Smør, Salt, Pepper, Hvitløk, Løk, Kokosmelk', '', 11, 'Smelt smør og stek løk til den er blank. Ha i hvitløk og stek i 1 minutt. Ha i currypaste og stek i 2 minutter. Ha i kokosmelk og oppkuttede gulrøtter og kok i 20-30 minutter til gulrøttene er møre. Bruk stavmikser for å få en jevn suppe. Smak til med salt og pepper.'),
       ('Lynrask linsegryte2', 'Hermetiske røde linser, Buljongterning, Currypaste, Olje, Salt, Pepper, Hvitløk, Løk, Kokosmelk, Hermetiske tomater', '', 3, 'Stek løk til den er blank. Ha i hvitløk og stek i 1 minutt. Ha i currypaste og stek i 2 minutter. Ha i buljong, kokosmelk og hermetiske tomater og kok opp i 5 minutter. Tilsett skylte linser. Smak til med salt og pepper.'),
       ('Bruschetta2', 'Mozzarella, Cherrytomater, Olivenolje, Salt, Pepper, Hvitløk, Basilikum, Brød', 'Gluten', 0, 'Ta skivet brød, pensle med olivenolje og stek de raskt i ovnen. Bland hakkede tomater, olivenolje, finhakket hvitløk, hakket basilikum, salt og pepper i en bolle. Fordel blandingen på brødskivene og topp med noen skiver mozzarella.');

INSERT INTO oppskrifter (Oppskriftstittel, Ingredienser, Allergier, Kategori, Oppskriftstekst)
VALUES ('Kålrabistappe3', 'Kålrot, Gulrøtter, Fløte, Smør, Salt, Pepper', 'Laktose', 5, 'Kok kålrot og gulrøtter. Mos mens du tilsetter smør og sper med fløte. Smak til med salt og pepper.'),
       ('Gulrotsuppe3', 'Gulrøtter, Currypaste, Smør, Salt, Pepper, Hvitløk, Løk, Kokosmelk', '', 11, 'Smelt smør og stek løk til den er blank. Ha i hvitløk og stek i 1 minutt. Ha i currypaste og stek i 2 minutter. Ha i kokosmelk og oppkuttede gulrøtter og kok i 20-30 minutter til gulrøttene er møre. Bruk stavmikser for å få en jevn suppe. Smak til med salt og pepper.'),
       ('Lynrask linsegryte3', 'Hermetiske røde linser, Buljongterning, Currypaste, Olje, Salt, Pepper, Hvitløk, Løk, Kokosmelk, Hermetiske tomater', '', 3, 'Stek løk til den er blank. Ha i hvitløk og stek i 1 minutt. Ha i currypaste og stek i 2 minutter. Ha i buljong, kokosmelk og hermetiske tomater og kok opp i 5 minutter. Tilsett skylte linser. Smak til med salt og pepper.'),
       ('Bruschetta3', 'Mozzarella, Cherrytomater, Olivenolje, Salt, Pepper, Hvitløk, Basilikum, Brød', 'Gluten', 0, 'Ta skivet brød, pensle med olivenolje og stek de raskt i ovnen. Bland hakkede tomater, olivenolje, finhakket hvitløk, hakket basilikum, salt og pepper i en bolle. Fordel blandingen på brødskivene og topp med noen skiver mozzarella.');

INSERT INTO oppskrifter (Oppskriftstittel, Ingredienser, Allergier, Kategori, Oppskriftstekst)
VALUES ('Kålrabistappe4', 'Kålrot, Gulrøtter, Fløte, Smør, Salt, Pepper', 'Laktose', 5, 'Kok kålrot og gulrøtter. Mos mens du tilsetter smør og sper med fløte. Smak til med salt og pepper.'),
       ('Gulrotsuppe4', 'Gulrøtter, Currypaste, Smør, Salt, Pepper, Hvitløk, Løk, Kokosmelk', '', 11, 'Smelt smør og stek løk til den er blank. Ha i hvitløk og stek i 1 minutt. Ha i currypaste og stek i 2 minutter. Ha i kokosmelk og oppkuttede gulrøtter og kok i 20-30 minutter til gulrøttene er møre. Bruk stavmikser for å få en jevn suppe. Smak til med salt og pepper.'),
       ('Lynrask linsegryte4', 'Hermetiske røde linser, Buljongterning, Currypaste, Olje, Salt, Pepper, Hvitløk, Løk, Kokosmelk, Hermetiske tomater', '', 3, 'Stek løk til den er blank. Ha i hvitløk og stek i 1 minutt. Ha i currypaste og stek i 2 minutter. Ha i buljong, kokosmelk og hermetiske tomater og kok opp i 5 minutter. Tilsett skylte linser. Smak til med salt og pepper.'),
       ('Bruschetta4', 'Mozzarella, Cherrytomater, Olivenolje, Salt, Pepper, Hvitløk, Basilikum, Brød', 'Gluten', 0, 'Ta skivet brød, pensle med olivenolje og stek de raskt i ovnen. Bland hakkede tomater, olivenolje, finhakket hvitløk, hakket basilikum, salt og pepper i en bolle. Fordel blandingen på brødskivene og topp med noen skiver mozzarella.');

INSERT INTO oppskrifter (Oppskriftstittel, Ingredienser, Allergier, Kategori, Oppskriftstekst)
VALUES ('Kålrabistappe5', 'Kålrot, Gulrøtter, Fløte, Smør, Salt, Pepper', 'Laktose', 5, 'Kok kålrot og gulrøtter. Mos mens du tilsetter smør og sper med fløte. Smak til med salt og pepper.'),
       ('Gulrotsuppe5', 'Gulrøtter, Currypaste, Smør, Salt, Pepper, Hvitløk, Løk, Kokosmelk', '', 11, 'Smelt smør og stek løk til den er blank. Ha i hvitløk og stek i 1 minutt. Ha i currypaste og stek i 2 minutter. Ha i kokosmelk og oppkuttede gulrøtter og kok i 20-30 minutter til gulrøttene er møre. Bruk stavmikser for å få en jevn suppe. Smak til med salt og pepper.'),
       ('Lynrask linsegryte5', 'Hermetiske røde linser, Buljongterning, Currypaste, Olje, Salt, Pepper, Hvitløk, Løk, Kokosmelk, Hermetiske tomater', '', 3, 'Stek løk til den er blank. Ha i hvitløk og stek i 1 minutt. Ha i currypaste og stek i 2 minutter. Ha i buljong, kokosmelk og hermetiske tomater og kok opp i 5 minutter. Tilsett skylte linser. Smak til med salt og pepper.'),
       ('Bruschetta5', 'Mozzarella, Cherrytomater, Olivenolje, Salt, Pepper, Hvitløk, Basilikum, Brød', 'Gluten', 0, 'Ta skivet brød, pensle med olivenolje og stek de raskt i ovnen. Bland hakkede tomater, olivenolje, finhakket hvitløk, hakket basilikum, salt og pepper i en bolle. Fordel blandingen på brødskivene og topp med noen skiver mozzarella.');

INSERT INTO oppskrifter (Oppskriftstittel, Ingredienser, Allergier, Kategori, Oppskriftstekst)
VALUES ('Kålrabistappe6', 'Kålrot, Gulrøtter, Fløte, Smør, Salt, Pepper', 'Laktose', 5, 'Kok kålrot og gulrøtter. Mos mens du tilsetter smør og sper med fløte. Smak til med salt og pepper.'),
       ('Gulrotsuppe6', 'Gulrøtter, Currypaste, Smør, Salt, Pepper, Hvitløk, Løk, Kokosmelk', '', 11, 'Smelt smør og stek løk til den er blank. Ha i hvitløk og stek i 1 minutt. Ha i currypaste og stek i 2 minutter. Ha i kokosmelk og oppkuttede gulrøtter og kok i 20-30 minutter til gulrøttene er møre. Bruk stavmikser for å få en jevn suppe. Smak til med salt og pepper.'),
       ('Lynrask linsegryte6', 'Hermetiske røde linser, Buljongterning, Currypaste, Olje, Salt, Pepper, Hvitløk, Løk, Kokosmelk, Hermetiske tomater', '', 3, 'Stek løk til den er blank. Ha i hvitløk og stek i 1 minutt. Ha i currypaste og stek i 2 minutter. Ha i buljong, kokosmelk og hermetiske tomater og kok opp i 5 minutter. Tilsett skylte linser. Smak til med salt og pepper.'),
       ('Bruschetta6', 'Mozzarella, Cherrytomater, Olivenolje, Salt, Pepper, Hvitløk, Basilikum, Brød', 'Gluten', 0, 'Ta skivet brød, pensle med olivenolje og stek de raskt i ovnen. Bland hakkede tomater, olivenolje, finhakket hvitløk, hakket basilikum, salt og pepper i en bolle. Fordel blandingen på brødskivene og topp med noen skiver mozzarella.');


